// <auto-generated />
using System;
using Advanced_Frontend_Final_Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Advanced_Frontend_Final_Api.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Advanced_Frontend_Final_Api.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Fname")
                        .HasColumnType("text")
                        .HasColumnName("fname");

                    b.Property<string>("Lname")
                        .HasColumnType("text")
                        .HasColumnName("lname");

                    b.Property<string>("Pfpurl")
                        .HasColumnType("text")
                        .HasColumnName("pfpurl");

                    b.HasKey("Id")
                        .HasName("person_pkey");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("Advanced_Frontend_Final_Api.Models.Temple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Lat")
                        .HasColumnType("text")
                        .HasColumnName("lat");

                    b.Property<string>("Long")
                        .HasColumnType("text")
                        .HasColumnName("long");

                    b.Property<string>("Mailaddress")
                        .HasColumnType("text")
                        .HasColumnName("mailaddress");

                    b.Property<string>("Photourl")
                        .HasColumnType("text")
                        .HasColumnName("photourl");

                    b.Property<string>("Templename")
                        .HasColumnType("text")
                        .HasColumnName("templename");

                    b.HasKey("Id")
                        .HasName("temple_pkey");

                    b.ToTable("temple", (string)null);
                });

            modelBuilder.Entity("Advanced_Frontend_Final_Api.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("Personid")
                        .HasColumnType("integer")
                        .HasColumnName("personid");

                    b.Property<int?>("Templeid")
                        .HasColumnType("integer")
                        .HasColumnName("templeid");

                    b.Property<DateTime?>("Visittime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("visittime");

                    b.HasKey("Id")
                        .HasName("visit_pkey");

                    b.HasIndex("Personid");

                    b.HasIndex("Templeid");

                    b.ToTable("visit", (string)null);
                });

            modelBuilder.Entity("Advanced_Frontend_Final_Api.Models.VisitPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Photourl")
                        .HasColumnType("text")
                        .HasColumnName("photourl");

                    b.Property<int?>("Visitid")
                        .HasColumnType("integer")
                        .HasColumnName("visitid");

                    b.HasKey("Id")
                        .HasName("visit_photo_pkey");

                    b.HasIndex("Visitid");

                    b.ToTable("visit_photo", (string)null);
                });

            modelBuilder.Entity("Advanced_Frontend_Final_Api.Models.Visit", b =>
                {
                    b.HasOne("Advanced_Frontend_Final_Api.Models.Person", "Person")
                        .WithMany("Visits")
                        .HasForeignKey("Personid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_person");

                    b.HasOne("Advanced_Frontend_Final_Api.Models.Temple", "Temple")
                        .WithMany("Visits")
                        .HasForeignKey("Templeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_temple");

                    b.Navigation("Person");

                    b.Navigation("Temple");
                });

            modelBuilder.Entity("Advanced_Frontend_Final_Api.Models.VisitPhoto", b =>
                {
                    b.HasOne("Advanced_Frontend_Final_Api.Models.Visit", "Visit")
                        .WithMany("VisitPhotos")
                        .HasForeignKey("Visitid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_visit");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Advanced_Frontend_Final_Api.Models.Person", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Advanced_Frontend_Final_Api.Models.Temple", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Advanced_Frontend_Final_Api.Models.Visit", b =>
                {
                    b.Navigation("VisitPhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
